### ISSUE TITLE
Adding missing unix tests

### ISSUE THREAD

**Issue by morettid** [StemVibrations/STEM#192]
Tests need to be added for Unix machines, which are now skipped:

Missing Unix-specific Kratos output:
-  benchmark_tests/test_moving_load_on_3_sections_3d/test_moving_load_on_3_sections_3d.py
-  benchmark_tests/test_random_field_3d/test_random_field_3d.py

Missing .so library for the UMAT:
-  benchmark_tests/test_1d_wave_prop_drained_soil_umat/test_1d_wave_prop_drained_soil_umat.py
- benchmark_tests/test_multi_stage_umat/test_multi_stage_umat.py

**Comment by aronnoordam** [comment]
-umats solved
random fields is not
