### ISSUE TITLE
bug in moving vtk files for multistage analysis

### ISSUE THREAD

**Issue by aronnoordam** [StemVibrations/STEM#218]
when the output interval is greater than the amount of time steps of the first stage in a multistage analysis. The output vtk files are not written, thus the ouput directory is not created. When trying to move vtk files from stage 2 to stage 1, it results in an error since the stage 1 dir is not there.

same issue would occur when any stage's number of steps is smaller than output interval

**Comment by EleniSmyrniou** [comment]
https://github.com/StemVibrations/STEM/pull/236
