### ISSUE TITLE
Add missing docstrings

### ISSUE THREAD

**Issue by brunozc** [StemVibrations/STEM#39]
Please add the missing docstring to the function GidOutputParameters in: stem/output.py

![image](https://github.com/StemVibrations/STEM/assets/15023286/8616fe39-f27b-4103-8917-4ef40a518ee7)

**Comment by morettid** [comment]
For those parameters, I couldn't find the exact description, not even in the source code of KRATOS:

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/gid_io.h

Any idea?

**Comment by aronnoordam** [comment]
The source code where these parameters are used can be found at :

~\Kratos\kratos\python_scripts\gid_output_process.py


But after seeing this i think the undescribed parameters can be removed entirely
