### ISSUE TITLE
give output on a point based on coordinates

### ISSUE THREAD

**Issue by aronnoordam** [StemVibrations/STEM#77]
currently, in STEM the mesh is generated following the geometry points, lines surfaces and volumes. However when a geometry point is given in the middle of a surface or volumes, the mesh is not generated through the point. 

- after generating mesh find element in which the obervation point is added. 
- add all nodes of that element to an output  model part
- after running the calculation, interpolated, results from the ouput model part nodes to the observation point

**Comment by morettid** [comment]
This also requires to re-think the outputs.

Option1:

outputs should take as input a list of body model parts, and then the submodel block for the output should only write all (or a portion of) the elements and nodes of the model parts.

For example:

output = Output( output_parameters = GidOutputParameters(...), part_name=__name__of__output_model_part, body_model_parts = [bmp1, bmp2, ... ], box_coords)

Where box_coords can be a square (2D) or a cube (3D) with all the nodes to be included in the model parts.
Then write only the elements with nodes falling in the box.
